import { AppController } from '@/app.controller';
import { AppService } from '@/app.service';
import { AuthModule } from '@/auth/auth.module';
import { AuthDto } from '@/auth/dto';
import { BookmarkModule } from '@/bookmark/bookmark.module';
import { PrismaModule } from '@/prisma/prisma.module';
import { PrismaService } from '@/prisma/prisma.service';
import { UserModule } from '@/user/user.module';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { Test } from '@nestjs/testing';
import * as pactum from 'pactum';

describe('App e2e', () => {
  let app: INestApplication;
  let prisma: PrismaService;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [
        ConfigModule.forRoot({ isGlobal: true }),
        AuthModule,
        UserModule,
        BookmarkModule,
        PrismaModule,
      ],
      controllers: [AppController],
      providers: [AppService],
    }).compile();

    // init app
    app = moduleRef.createNestApplication();
    app.useGlobalPipes(new ValidationPipe({ whitelist: true }));
    await app.init();
    await app.listen(4001);

    // delete all data in test DB
    prisma = app.get(PrismaService);
    await prisma.cleanDB();

    pactum.request.setBaseUrl('http://localhost:4001');
  });

  afterAll(() => {
    app.close();
  });

  describe('Auth', () => {
    const dto: AuthDto = {
      email: 'test@gmail.com',
      password: 'Password',
    };
    describe('Signup', () => {
      it('201 when valid email and password', () => {
        return pactum
          .spec()
          .post('/auth/signup')
          .withBody(dto)
          .expectStatus(201);
        // .inspect(); can show content of response
      });
      it('400 when email empty', () => {
        return pactum
          .spec()
          .post('/auth/signup')
          .withBody({ email: '', password: 'Password' })
          .expectStatus(400);
      });
      it('400 when password empty', () => {
        return pactum
          .spec()
          .post('/auth/signup')
          .withBody({ email: 'valid@gmail.com', password: '' })
          .expectStatus(400);
      });
      it('403 if email is not unique', () => {
        return pactum
          .spec()
          .post('/auth/signup')
          .withBody(dto)
          .expectStatus(403);
      });
    });
    describe('Login', () => {
      it('should login', () => {
        return pactum
          .spec()
          .post('/auth/login')
          .withBody(dto)
          .expectStatus(200);
      });
    });
  });
  describe('User', () => {
    describe('Get me', () => {
      it.todo('should get current user info');
    });
    describe('Edit user', () => {
      it.todo('should change user info');
    });
  });
  describe('Bookmark', () => {
    describe('Create new bookmark', () => {
      it.todo('new bookmark saved to DB');
    });
    describe('Get bookmarks', () => {
      it.todo('get all bookmarks');
    });
    describe('Get bookmark by id', () => {
      it.todo('get the bookmark');
    });
    describe('Edit bookmark', () => {
      it.todo('change the bookmark data and saved it to DB');
    });
    describe('Delete bookmark', () => {
      it.todo('delete the bookmark from DB');
    });
  });
});

// nest autogenerated app e2e test code below
// import { Test, TestingModule } from '@nestjs/testing';
// import { INestApplication } from '@nestjs/common';
// import * as request from 'supertest';
// import { AppModule } from './../src/app.module';

// describe('AppController (e2e)', () => {
//   let app: INestApplication;

//   beforeEach(async () => {
//     const moduleFixture: TestingModule = await Test.createTestingModule({
//       imports: [AppModule],
//     }).compile();

//     app = moduleFixture.createNestApplication();
//     await app.init();
//   });

//   it('/ (GET)', () => {
//     return request(app.getHttpServer())
//       .get('/')
//       .expect(200)
//       .expect('Hello World!');
//   });
// });
