import { AppController } from '@/app.controller';
import { AppService } from '@/app.service';
import { AuthModule } from '@/auth/auth.module';
import { BookmarkModule } from '@/bookmark/bookmark.module';
import { PrismaModule } from '@/prisma/prisma.module';
import { PrismaService } from '@/prisma/prisma.service';
import { UserModule } from '@/user/user.module';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { Test } from '@nestjs/testing';

describe('App e2e', () => {
  let app: INestApplication;
  let prisma: PrismaService;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [
        ConfigModule.forRoot({ isGlobal: true }),
        AuthModule,
        UserModule,
        BookmarkModule,
        PrismaModule,
      ],
      controllers: [AppController],
      providers: [AppService],
    }).compile();

    // init app
    app = moduleRef.createNestApplication();
    app.useGlobalPipes(new ValidationPipe({ whitelist: true }));
    await app.init();

    // delete all data in test DB
    prisma = app.get(PrismaService);
    await prisma.cleanDB();
  });

  afterAll(() => {
    app.close();
  });

  describe('Auth', () => {
    describe('Signup', () => {
      it.todo('should signup');
    });
    describe('Login', () => {
      it.todo('should login');
    });
  });
  describe('User', () => {
    describe('Get me', () => {
      it.todo('should get current user info');
    });
    describe('Edit user', () => {
      it.todo('should change user info');
    });
  });
  describe('Bookmark', () => {
    describe('Create new bookmark', () => {
      it.todo('new bookmark saved to DB');
    });
    describe('Get bookmarks', () => {
      it.todo('get all bookmarks');
    });
    describe('Get bookmark by id', () => {
      it.todo('get the bookmark');
    });
    describe('Edit bookmark', () => {
      it.todo('change the bookmark data and saved it to DB');
    });
    describe('Delete bookmark', () => {
      it.todo('delete the bookmark from DB');
    });
  });
});

// nest autogenerated app e2e test code below
// import { Test, TestingModule } from '@nestjs/testing';
// import { INestApplication } from '@nestjs/common';
// import * as request from 'supertest';
// import { AppModule } from './../src/app.module';

// describe('AppController (e2e)', () => {
//   let app: INestApplication;

//   beforeEach(async () => {
//     const moduleFixture: TestingModule = await Test.createTestingModule({
//       imports: [AppModule],
//     }).compile();

//     app = moduleFixture.createNestApplication();
//     await app.init();
//   });

//   it('/ (GET)', () => {
//     return request(app.getHttpServer())
//       .get('/')
//       .expect(200)
//       .expect('Hello World!');
//   });
// });
