version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./env/mysql.env
    ports:
      - 3306:3306
  mysql-test:
    image: mysql:8.0
    container_name: mysql-test
    env_file:
      - ./env/mysql.env
    ports:
      - 3307:3306